# 固有値分解/特異値分解

In [1]:
# linalgモジュールはLAとしてimportする
import numpy as np
import numpy.linalg as LA

#2次正方行列Aを定義する
a = np.array([[5, 2],[2, 5]])

# 2 次正方行列 Aの固有値、固有ベクトルPを計算する
l, p = LA.eig(a)
print("固有値")
print(l)  # 固有値
print("固有ベクトル P ")
print(p)  # 固有ベクトル(正規化済)

#対角行列D、Pの逆行列P-1を定義
d = np.array([[l[0],0],[0,l[1]]])
pinv = LA.inv(p)

#固有値分解の確認（P＊D＊P-1） 行列Aが算出される
print("固有値分解 確認 A = P x D x P-1")
print(np.dot(np.dot(p,d),pinv))

固有値
[7. 3.]
固有ベクトル P 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
固有値分解 確認 A = P x D x P-1
[[5. 2.]
 [2. 5.]]


In [2]:
# linalgモジュールはLAとしてimportする
import numpy as np
import numpy.linalg as LA

#2次正方行列Aを定義する
a = np.array([[5, 2],[2, 5]])

# 2 次正方行列 U,Σ,V(転置行列)を求める
U, S, Vt = LA.svd(a, full_matrices=True)
print("左特異値ベクトルを列として並べた２次正方行列 U")
print(U)
print("特異値以外を0で埋めた２次正方行列 Σ")
print(np.diag(S))
print("右特異値ベクトルを列として並べた２次正方行列 V")
print(Vt)

#特異値分解の確認（U＊Σ＊Vt） 行列Aが算出される
print("固有値分解 確認 A = U x Σ x Vt")
print(np.dot(np.dot(U,np.diag(S)),Vt))

左特異値ベクトルを列として並べた２次正方行列 U
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
特異値以外を0で埋めた２次正方行列 Σ
[[7. 0.]
 [0. 3.]]
右特異値ベクトルを列として並べた２次正方行列 V
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
固有値分解 確認 A = U x Σ x Vt
[[5. 2.]
 [2. 5.]]
